### ISSUE TITLE
Would you be able to provide trained model?

### ISSUE THREAD

**Issue by Guptajakala** [vinits5/pointnet-registration-framework#1]

**Comment by vinits5** [comment]
Please take a look at the following links. Repository PointNetLK has pre-trained models for PointNetLK.
Link for Pretrained Model for PCRNet: https://drive.google.com/drive/u/1/folders/1o3F6677n6FVuMArNVWTyP5Hn3m856eEG
Link for Pretrained Model for PointNetLK: https://github.com/vinits5/PointNetLK
